### ISSUE TITLE
License

### ISSUE THREAD

**Issue by YauheniK172** [guardian/elasticsearch-node-rotation#77]
Hi,

We want to use your step function for one project.
Can you tell us what the license is?

**Comment by jacobwinch** [comment]
Thanks for your interest in the project! 

Thanks also for pointing out the omission of a license, which has now been added: https://github.com/guardian/elasticsearch-node-rotation/pull/78.

The Step Function has been designed based on a number of assumptions about the underlying AWS infrastructure / Elasticsearch cluster configuration in order to work with The Guardian's clusters. You may need to experiment and make some adjustments before using this Step Function with your own project.

Thanks again!
